AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CourtVision AI - Iowa Hawkeyes Basketball Analytics API

Globals:
  Function:
    Timeout: 10
    Runtime: python3.12
    MemorySize: 256
    Environment:
      Variables:
        TABLE_NAME: courtvision-games
        REGION: us-east-1

Resources:
  # API Gateway
  CourtVisionApi:
      Type: AWS::Serverless::Api
      Properties:
        Name: courtvision-api
        StageName: prod
        Cors:
          AllowMethods: "'GET,OPTIONS'"
          AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
          AllowOrigin: "'*'"

  # Lambda: Get all games for a season
  GetGamesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: courtvision-get-games
      CodeUri: lambdas/get_games/
      Handler: lambda_function.handler
      Description: List all games for a season
      Policies:
        - DynamoDBReadPolicy:
            TableName: courtvision-games
      Events:
        GetGames:
          Type: Api
          Properties:
            RestApiId: !Ref CourtVisionApi
            Path: /games
            Method: get

  # Lambda: Get single game details
  GetGameDetailFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: courtvision-get-game-detail
      CodeUri: lambdas/get_game_detail/
      Handler: lambda_function.handler
      Description: Get game metadata and boxscore
      Policies:
        - DynamoDBReadPolicy:
            TableName: courtvision-games
      Events:
        GetGameDetail:
          Type: Api
          Properties:
            RestApiId: !Ref CourtVisionApi
            Path: /games/{gameId}
            Method: get

  # Lambda: Get plays for a game
  GetPlaysFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: courtvision-get-plays
      CodeUri: lambdas/get_plays/
      Handler: lambda_function.handler
      Description: Get play-by-play data for a game
      Policies:
        - DynamoDBReadPolicy:
            TableName: courtvision-games
      Events:
        GetPlays:
          Type: Api
          Properties:
            RestApiId: !Ref CourtVisionApi
            Path: /games/{gameId}/plays
            Method: get

  # Lambda: Get players with aggregated stats
  GetPlayersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: courtvision-get-players
      CodeUri: lambdas/get_players/
      Handler: lambda_function.handler
      Description: Get aggregated player statistics for a season
      Timeout: 30
      MemorySize: 512
      Policies:
        - DynamoDBReadPolicy:
            TableName: courtvision-games
      Events:
        GetPlayers:
          Type: Api
          Properties:
            RestApiId: !Ref CourtVisionApi
            Path: /players
            Method: get

  GetSeasonStatsFunction:
      Type: AWS::Serverless::Function
      Properties:
        FunctionName: courtvision-get-season-stats
        CodeUri: lambdas/get_season_stats/
        Handler: lambda_function.handler
        Runtime: python3.11
        Timeout: 30
        MemorySize: 256
        Environment:
          Variables:
            TABLE_NAME: courtvision-games
            REGION: us-east-1
        Policies:
          - DynamoDBReadPolicy:
              TableName: courtvision-games
        Events:
          GetStats:
            Type: Api
            Properties:
              Path: /stats
              Method: get
              RestApiId: !Ref CourtVisionApi

  # Lambda: Generate AI Game Summary
  AIGameSummaryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: courtvision-ai-game-summary
      CodeUri: lambdas/ai_game_summary/
      Handler: lambda_function.handler
      Runtime: python3.12
      Timeout: 30
      MemorySize: 512
      Environment:
        Variables:
          TABLE_NAME: courtvision-games
          REGION: us-east-1
      Policies:
        - DynamoDBCrudPolicy:
            TableName: courtvision-games
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: "arn:aws:bedrock:us-east-1::foundation-model/anthropic.claude-3-5-sonnet-20240620-v1:0"
      Events:
        GetAISummary:
          Type: Api
          Properties:
            RestApiId: !Ref CourtVisionApi
            Path: /games/{gameId}/summary
            Method: get

  # Lambda: Reddit Sentiment Analysis
  RedditSentimentFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: courtvision-reddit-sentiment
      CodeUri: lambdas/reddit_sentiment/
      Handler: lambda_function.handler
      Runtime: python3.12
      Timeout: 30
      MemorySize: 512
      Environment:
        Variables:
          TABLE_NAME: courtvision-games
          REGION: us-east-1
      Policies:
        - DynamoDBCrudPolicy:
            TableName: courtvision-games
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: "arn:aws:bedrock:us-east-1::foundation-model/anthropic.claude-3-5-sonnet-20240620-v1:0"
      Events:
        GetRedditSentiment:
          Type: Api
          Properties:
            RestApiId: !Ref CourtVisionApi
            Path: /games/{gameId}/sentiment
            Method: get
  
Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${CourtVisionApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
  
  GetGamesFunction:
    Description: Get Games Lambda Function ARN
    Value: !GetAtt GetGamesFunction.Arn

  GetPlayersFunction:
    Description: Get Players Lambda Function ARN
    Value: !GetAtt GetPlayersFunction.Arn